'''
Created on May 20, 2012

@author: husnusensoy
'''


'''
    Print metrics generated by evaluation functions
        noverlap: Total number of shared constituents by gold trees/graphs and model tree/graphs
        ngolden: Total number of shared constituents by gold trees/graphs
        nmodel: Total number of shared constituents by model tree/graphs
'''
def print_metrics(noverlap, ngolden, nmodel):
    precision = noverlap * 1.0 / nmodel
    recall = noverlap * 1.0 / ngolden
    f1score = 2 * ((precision * recall) / (precision + recall))

    print "\tUnsupervised Precision (UP)\t{:.2%}".format(precision)
    print "\tUnsupervised Recall (UR)\t{:.2%}".format(recall)
    print "\tUnsupervised F1 Score (UF1)\t{:.2%}".format(f1score)
    print
    print "\t# of Constituents Matched\t%d" % (noverlap)
    print "\t# of Constituents by Model\t%d" % (nmodel)
    print "\t# of Constituents by Gold\t%d" % (ngolden)